// export const host="http://localhost:2500"
export const host="https://let-us-discuss-server.vercel.app"
export const registerRoute=`${host}/api/auth/register`
export const loginRoute=`${host}/api/auth/login`
export const allUsersRoute=`${host}/api/auth/allUsers`
export const fileUploadRoute=`${host}/api/auth/upload`
export const editUserRoute=`${host}/api/auth/editUser`
export const sendMessageRoute=`${host}/api/messages/sendMessage`
export const getcurrentChatMessagesRoute=`${host}/api/messages/currentChatMessages`
export const getAllMessagesRoute=`${host}/api/messages/getAllMessages`
export const createGroupRoute=`${host}/api/group/create-group`
export const getGroupsRoute=`${host}/api/group/get-groups`
export const addMemberRoute=`${host}/api/group/addMember`
export const getMembersRoute=`${host}/api/group/getMembers`
export const sendMessageToGroupRoute=`${host}/api/group/send_group_message`
export const groupMessagesRoute=`${host}/api/group/get_group_message`
export const groupFileUploadRoute=`${host}/api/group/Upload`
export const groupNameUpdateRoute=`${host}/api/group/update`
